### PR TITLE
Convert Numbers to .NetStandard 1.0 library

### PR DESCRIPTION
**Pull request by NZSmartie**
Moving this project to .Net Standard enables new projects (such as those using .Net Core) to take advantage of this project.

I'm not great at creating a compelling argument. But for my use case, I'm building a set of libraries in .Net Standard that do not work with a .Net Portable library.

### CODE REVIEW

**Comment by NZSmartie** [comment]
I also intend to convert https://github.com/peteroupc/CBOR into a .Net Standard library as well, but requires this library, so starting here first

**Comment by tabrath** [comment]
@NZSmartie project.json is deprecated in favor of .csproj files now. See [here](https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj) for context.

**Comment by NZSmartie** [comment]
Interesting, I've been aware it's being deprecated, but unsure why Visual Studio 2017 will still `project.json` when `Numbers.csproj` is present. 
I'm currently fighting with Visual Studio 2017 to manage nuget packages in the .csproj using PackageReference (http://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html#what-about-other-project-types-that-are-not-net-core) but it's being persistent that it uses NuGet 3.0 with it's project.json
Hopefully I'll figure out how to move past project.json and update this PR soon.

**Comment by NZSmartie** [comment]
So I had to re-create `Numbers.csproj` from scratch in order to get the new MSBuild stuff. Which solved Visual Studio wanting to create `project.json`.

Though, I've removed the build configuration for .Net 4.0 since it doesn't support .Net Standard 1.0. If it's required I can look into getting that working some how

**Comment by peteroupc** [comment]
I have two questions:

- Are you releasing your contribution under the Creative Commons Zero (public domain) declaration (see the LICENSE file)?
- Do you know the market share for .NET versions 4.0 and older in comparison with newer versions?  The answer will guide whether a .NET 4.0 version is still worthwhile.

**Comment by tabrath** [comment]
Support for 4.0 ended last year, as stated [here](https://redmondmag.com/articles/2016/01/04/microsoft-support-ending-in-2016-for-ie.aspx).

**Comment by peteroupc** [comment]
Fair enough.  I strike out my second question.

**Comment by peteroupc** [comment]
@NZSmartie: Are you releasing your contribution to the public domain under Creative Commons Zero?

**Comment by peteroupc** [comment]
Note that you moved Numbers.nuspec to Numbers.csproj, which is no longer a C# project.

**Comment by peteroupc** [comment]
I've finished adapting your change.  I hope you don't mind.

**Pull request merged**
